# Generated by Django 3.2 on 2021-05-09 22:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_images_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
