# Generated by Django 3.2 on 2021-05-10 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='car.car'),
        ),
    ]
