# Generated by Django 3.2 on 2021-06-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_auto_20210613_1954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryAdmin',
        ),
    ]
