# Generated by Django 3.2 on 2021-06-18 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0010_delete_categoryadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_at',
            new_name='create_up',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_at',
            new_name='update_up',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Benzin', 'Benzin'), ('LPG', 'LPG'), ('Dizel', 'Dizel'), ('Hybrid', 'Hybrid')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='gear',
            field=models.CharField(choices=[('Manuel', 'Manuel'), ('Otomatik', 'Otomatik'), ('Yarı Otomatik', 'Yarı Otomatik')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='km',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='motorpower',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='situation',
            field=models.CharField(choices=[('Cabrio', 'Cabrio'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Sedan', 'Sedan')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
