# Generated by Django 3.2 on 2021-06-30 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_alter_car_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(default=uuid.uuid1),
        ),
    ]
