# Generated by Django 3.2 on 2021-06-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_alter_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Benzin', 'Benzin'), ('LPG', 'LPG'), ('Dizel', 'Dizel'), ('Hybrid', 'Hybrid')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='gear',
            field=models.CharField(choices=[('Manuel', 'Manuel'), ('Otomatik', 'Otomatik'), ('Yarı Otomatik', 'Yarı Otomatik')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='km',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='motorpower',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='situation',
            field=models.CharField(choices=[('Cabrio', 'Cabrio'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Sedan', 'Sedan')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
