# Generated by Django 3.2 on 2021-06-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(),
        ),
    ]
