# Generated by Django 3.2 on 2021-07-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cimages',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
